title: Adenan Yandra Nofrizal Journey
description: Remote sensing and geospatial researcher. with a particular focus on the utilisation of hyperspectral data in the context of vegetation traits and ecological analysis. In order to achieve my research objectives, I have employed a range of techniques, including machine learning and radiative transfer models (RTMs).
logo: /assets/hyper.png
theme: jekyll-theme-minimal
